# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-docstring-first
        exclude: tests
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-symlinks
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '(\.idea/|\.iml$)'
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: browser/tests/utils.py
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--preview"]
        language_version: python3.12
      - id: ruff-format
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # use the latest stable version
    hooks:
      - id: mypy
        name: mypy type check
        entry: mypy
        language: python
        types: [python]
        additional_dependencies: []

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
